"""empty message

Revision ID: 30cdc559fbd3
Revises: c39226328ae8
Create Date: 2017-12-26 08:01:53.692850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cdc559fbd3'
down_revision = 'c39226328ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publish', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'publish')
    # ### end Alembic commands ###
