"""empty message

Revision ID: 36729fb869bd
Revises: 1f3f236fa8aa
Create Date: 2017-12-27 15:12:55.809729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36729fb869bd'
down_revision = '1f3f236fa8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
