"""empty message

Revision ID: 6a65dc48303e
Revises: 84ec3202f781
Create Date: 2017-12-19 12:26:02.520101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a65dc48303e'
down_revision = '84ec3202f781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###
