"""empty message

Revision ID: cfee4c7b44ac
Revises: a7b02ff68072
Create Date: 2018-01-04 08:12:35.448377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfee4c7b44ac'
down_revision = 'a7b02ff68072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_tag_tag_name'), 'tag', ['tag_name'], unique=False)
    op.drop_column('tag', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag')
    op.drop_column('tag', 'tag_name')
    # ### end Alembic commands ###
