"""empty message

Revision ID: d93c1ebbb74f
Revises: 670c9982c603
Create Date: 2017-12-30 08:06:40.338648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93c1ebbb74f'
down_revision = '670c9982c603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tags', sa.String(length=200), nullable=True))
    op.drop_column('tags', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('tags', 'tags')
    # ### end Alembic commands ###
